# Generated by Django 5.0.2 on 2024-03-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0007_delete_expensecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
