# Generated by Django 5.0.2 on 2024-02-29 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0006_expensecategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
    ]
