# Generated by Django 5.0.2 on 2024-02-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0002_rename_categoryname_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Housing', 'Housing'), ('Transportation', 'Transportation'), ('Food', 'Food')], max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(choices=[('Rent/Mortgage', 'Rent/Mortgage'), ('Vehicle Maintenance', 'Vehicle Maintenance'), ('Fast Food', 'Fast Food')], max_length=100),
        ),
    ]
