# Generated by Django 5.0.2 on 2024-02-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='salary',
        ),
        migrations.AddField(
            model_name='user',
            name='Firstname',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Lastname',
            field=models.CharField(null=True),
        ),
    ]
